# Image dimensions
image:
  width: 56
  height: 56
# Background generation parameters
background:
  num_backgrounds: 10  # Number of backgrounds to generate
  scale:
    min: 2.0
    max: 20.0
  octaves:
    min: 2
    max: 10
  persistence:
    min: 0.1
    max: 0.9
  lacunarity:
    min: 1.0
    max: 3.0

# Output directory
output:
  base_dir: "../datasets/action-drawing-agent"

# Generation parameters
generation:
  num_videos: 100

# Video parameters
video:
  show_compass: 0.5  # Percentage of videos that will have the compass displayed (0.0 to 1.0)
  fixed_background: true  # Set to true to use the same background throughout the video

# Curve lines dataset parameters
curve_lines_dataset:
  num_samples_per_class: 100  # Number of samples per class (straight lines and curves)
  num_translations_per_shape: 8  # Number of translated versions per base shape

# Mask parameters for masked videos
mask:
  aspect_ratio:
    - 0.75
    - 1.5
  num_blocks: 8
  spatial_scale:
    - 0.15
    - 0.15
  temporal_scale:
    - 1.0
    - 1.0