# Image dimensions
image:
  width: 56
  height: 56
# Background generation parameters
background:
  num_backgrounds: 10  # Number of backgrounds to generate
  include_black: true  # Whether to include completely black backgrounds
  black_probability: 1.0  # Probability of generating a black background (0.0 to 1.0)
  scale:
    min: 2.0
    max: 20.0
  octaves:
    min: 2
    max: 10
  persistence:
    min: 0.1
    max: 0.9
  lacunarity:
    min: 1.0
    max: 3.0

# Output directory
output:
  base_dir: "../shared/datasets/action-drawing-agent/one-folder-dataset/19200-videos"

# Generation parameters
generation:
  num_videos: 19200

# Video parameters
video:
  - folder_name: "videos_with_action"
    show_compass: 0.8  # Percentage of videos that will have the compass displayed (0.0 to 1.0)
    fixed_background: true  # Set to true to use the same background throughout the video 
    pause_probability: 0.0  # Probability of having a pause in a video (0.0 to 1.0, 0.0 disables pauses)
  - folder_name: "videos_no_action"
    show_compass: 0.2  # Percentage of videos that will have the compass displayed (0.0 to 1.0)
    fixed_background: true  # Set to true to use the same background throughout the video
    pause_probability: 0.0  # Probability of having a pause in a video (0.0 to 1.0, 0.0 disables pauses)

# Curve lines dataset parameters
curve_lines_dataset:
  - folder_name: "curve_lines_dataset_100"
    num_samples_per_class: 100
    num_translations_per_shape: 5  # Number of translated versions per base shape
  - folder_name: "curve_lines_dataset_200"
    num_samples_per_class: 200
    num_translations_per_shape: 5  # Number of translated versions per base shape
  - folder_name: "curve_lines_dataset_400"
    num_samples_per_class: 400  # Number of samples per class (straight lines and curves)
    num_translations_per_shape: 5  # Number of translated versions per base shape

# Letter dataset parameters
letter_dataset:
  - folder_name: "letter_dataset_ach_100"
    num_samples_per_class: 100
    num_translations_per_shape: 5  # Number of translated versions per base shape
    letters: ['a', 'c', 'h']  # Letters to generate
  - folder_name: "letter_dataset_ach_200"
    num_samples_per_class: 200
    num_translations_per_shape: 5  # Number of translated versions per base shape
    letters: ['a', 'c', 'h']  # Letters to generate
  - folder_name: "letter_dataset_achos_100"
    num_samples_per_class: 100
    num_translations_per_shape: 5  # Number of translated versions per base shape
    letters: ['a', 'c', 'h', 'o', 's']  # Letters to generate
