# Image dimensions
image:
  width: 56
  height: 56
# Background generation parameters
background:
  num_backgrounds: 10  # Number of backgrounds to generate
  include_black: true  # Whether to include completely black backgrounds
  black_probability: 1.0  # Probability of generating a black background (0.0 to 1.0)
  scale:
    min: 2.0
    max: 20.0
  octaves:
    min: 2
    max: 10
  persistence:
    min: 0.1
    max: 0.9
  lacunarity:
    min: 1.0
    max: 3.0

# Output directory
output:
  base_dir: "../datasets/action-drawing-agent/videos_with_action/12800-videos"

# Generation parameters
generation:
  num_videos: 12800

# Video parameters
video:
  show_compass: 0.7  # Percentage of videos that will have the compass displayed (0.0 to 1.0)
  fixed_background: true  # Set to true to use the same background throughout the video
  compass_margin: 10  # Top margin for compass display in pixels
  pause_probability: 0.5  # Probability of having a pause in a video (0.0 to 1.0, 0.0 disables pauses)

# Curve lines dataset parameters
curve_lines_dataset:
  num_samples_per_class: 50000  # Number of samples per class (straight lines and curves)
  num_translations_per_shape: 8  # Number of translated versions per base shape

# Mask parameters for masked videos
mask:
  aspect_ratio:
    - 0.75
    - 1.5
  num_blocks: 8
  spatial_scale:
    - 0.15
    - 0.15
  temporal_scale:
    - 1.0
    - 1.0