# Image dimensions
image:
  width: 56
  height: 56

# Background generation parameters
background:
  num_backgrounds: 1000  # Number of backgrounds to generate
  scale:
    min: 2.0
    max: 20.0
  octaves:
    min: 2
    max: 10
  persistence:
    min: 0.1
    max: 0.9
  lacunarity:
    min: 1.0
    max: 3.0

# Output directory
output:
  base_dir: "../datasets/drawing-agent-test"

# Generation parameters
generation:
  num_videos: 200 